export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_FOUND: 'EMAIL_NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCOUNT_NOT_LINKED: 'ACCOUNT_NOT_LINKED',
  OAUTH_ERROR: 'OAUTH_ERROR',
  INVALID_FIELDS: 'INVALID_FIELDS',
  RATE_LIMITED: 'RATE_LIMITED',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED',
  GENERIC_FAILURE: 'GENERIC_FAILURE',
  TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_ALREADY_USED: 'TOKEN_ALREADY_USED',
  EMAIL_SEND_ERROR: 'EMAIL_SEND_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
