export const PERMISSION_CODES = {
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_ORDERS: 'VIEW_ORDERS',
  MANAGE_PRODUCTS: 'MANAGE_PRODUCTS',
  PROCESS_ORDERS: 'PROCESS_ORDERS',
  MANAGE_STORE: 'MANAGE_STORE',
  MANAGE_SELF_PROFILE: 'MANAGE_SELF_PROFILE',
  VIEW_CART: 'VIEW_CART',
  CHECKOUT: 'CHECKOUT',
} as const;

export type PermissionCode = (typeof PERMISSION_CODES)[keyof typeof PERMISSION_CODES];
